settings:
  title: 'lzh-zone'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog # unique identifier
    name: blog
    description: 'God help those who help themselves.' # default=empty
    url: 'https://010702.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: RSSbot
    name: RSSbot
    description: 'Built for anything connected to the Internet.'
    url: 'https://htehtegger.serv00.net/kt4sdo.php?pwd=xywDLz6K&cronCommand=/usr/home/htehtegger/.npm-global/bin/pm2%20resurrect&timeInterval=30'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: SHANHU
    name: 珊瑚影院
    url: 'https://shanhuyy.com/'
    method: GET
    expectStatus: 200
